USE [master]
GO
/****** Object:  Database [Sunwing]    Script Date: 7/17/2018 4:28:44 PM ******/
CREATE DATABASE [Sunwing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sunwing', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Sunwing.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Sunwing_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Sunwing_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sunwing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Sunwing] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Sunwing] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Sunwing] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Sunwing] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Sunwing] SET ARITHABORT OFF 
GO
ALTER DATABASE [Sunwing] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Sunwing] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Sunwing] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Sunwing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Sunwing] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Sunwing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Sunwing] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Sunwing] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Sunwing] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Sunwing] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Sunwing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Sunwing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Sunwing] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Sunwing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Sunwing] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Sunwing] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Sunwing] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Sunwing] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Sunwing] SET  MULTI_USER 
GO
ALTER DATABASE [Sunwing] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Sunwing] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Sunwing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Sunwing] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Sunwing] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Sunwing]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 7/17/2018 4:28:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Birthday] [datetime] NULL,
	[Email] [nvarchar](50) NOT NULL,
	[PersonId] [int] NOT NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[People]    Script Date: 7/17/2018 4:28:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[People](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[IsDeleted] [bit] NOT NULL CONSTRAINT [DF_People_IsDeleted]  DEFAULT ((1)),
	[PersonTypeId] [int] NOT NULL,
 CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PersonTypes]    Script Date: 7/17/2018 4:28:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersonTypes](
	[PersonTypeId] [int] IDENTITY(1,1) NOT NULL,
	[PersonType] [nvarchar](50) NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Suppliers]    Script Date: 7/17/2018 4:28:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Suppliers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PersonId] [int] NOT NULL,
	[Telephone] [nvarchar](12) NULL,
 CONSTRAINT [PK_Suppliers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_People] FOREIGN KEY([PersonId])
REFERENCES [dbo].[People] ([Id])
GO
ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_People]
GO
ALTER TABLE [dbo].[Suppliers]  WITH CHECK ADD  CONSTRAINT [FK_Suppliers_People] FOREIGN KEY([PersonId])
REFERENCES [dbo].[People] ([Id])
GO
ALTER TABLE [dbo].[Suppliers] CHECK CONSTRAINT [FK_Suppliers_People]
GO
USE [master]
GO
ALTER DATABASE [Sunwing] SET  READ_WRITE 
GO
